name: PR deploy

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [
            'lint:check',
            #'test',
            'build',
          ]
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn ${{ matrix.step }}

  deploy-to-firebase:
    runs-on: ubuntu-latest
    needs: build
    environment: develop
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install and Build 🔧
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          # FOR BUILD
          VITE_NODE_ENV: develop

          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          VITE_SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

          VITE_GITHUB_HASH: ${{ github.sha }}

      # Disribute to Firebase
      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}'
          expires: 14d
